#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker
- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose-v2
    state: present
    update_cache: true
- name: Start Docker service and enable it on boot
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: true